from PySide2 import QtCore, QtWidgets, QtGui


class Blast:

    def __init__(self, parent, Dialog):
        parent.FORMTAS = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parent.FORMTAS.sizePolicy().hasHeightForWidth())
        parent.FORMTAS.setSizePolicy(sizePolicy)
        parent.FORMTAS.setObjectName("FORMTAS")
        parent.mainLayout.addWidget(parent.FORMTAS)
        parent.listFormat = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parent.listFormat.sizePolicy().hasHeightForWidth())
        parent.listFormat.setSizePolicy(sizePolicy)
        parent.listFormat.setObjectName("listFormat")
        parent.mainLayout.addWidget(parent.listFormat)
        parent.CAMERAS = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parent.CAMERAS.sizePolicy().hasHeightForWidth())
        parent.CAMERAS.setSizePolicy(sizePolicy)
        parent.CAMERAS.setObjectName("CAMERAS")
        parent.mainLayout.addWidget(parent.CAMERAS)
        parent.listCameras = QtWidgets.QComboBox(Dialog)
        parent.listCameras.setObjectName("listCameras")
        parent.mainLayout.addWidget(parent.listCameras)
        parent.FRAMERANGE = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parent.FRAMERANGE.sizePolicy().hasHeightForWidth())
        parent.FRAMERANGE.setSizePolicy(sizePolicy)
        parent.FRAMERANGE.setObjectName("FRAMERANGE")
        parent.mainLayout.addWidget(parent.FRAMERANGE)
        parent.framerange = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parent.framerange.sizePolicy().hasHeightForWidth())
        parent.framerange.setSizePolicy(sizePolicy)
        parent.framerange.setObjectName("framerange")
        parent.layoutFramgeRange = QtWidgets.QHBoxLayout(parent.framerange)
        parent.layoutFramgeRange.setContentsMargins(0, 0, 0, 0)
        parent.layoutFramgeRange.setSpacing(8)
        parent.layoutFramgeRange.setObjectName("layoutFramgeRange")
        parent.frameRangeOptions = QtWidgets.QComboBox(parent.framerange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parent.frameRangeOptions.sizePolicy().hasHeightForWidth())
        parent.frameRangeOptions.setSizePolicy(sizePolicy)
        parent.frameRangeOptions.setObjectName("frameRangeOptions")
        parent.layoutFramgeRange.addWidget(parent.frameRangeOptions)
        parent.frame_in = QtWidgets.QSpinBox(parent.framerange)
        parent.frame_in.setMaximumSize(QtCore.QSize(80, 16777215))
        parent.frame_in.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        parent.frame_in.setMaximum(9999)
        parent.frame_in.setObjectName("frame_in")
        parent.layoutFramgeRange.addWidget(parent.frame_in)
        parent.frame_out = QtWidgets.QSpinBox(parent.framerange)
        parent.frame_out.setMinimumSize(QtCore.QSize(0, 0))
        parent.frame_out.setMaximumSize(QtCore.QSize(80, 16777215))
        parent.frame_out.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        parent.frame_out.setMaximum(9999)
        parent.frame_out.setObjectName("frame_out")
        parent.layoutFramgeRange.addWidget(parent.frame_out)
        parent.mainLayout.addWidget(parent.framerange)
        parent.line = QtWidgets.QFrame(Dialog)
        parent.line.setFrameShape(QtWidgets.QFrame.HLine)
        parent.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        parent.line.setObjectName("line")
        parent.mainLayout.addWidget(parent.line)
        parent.footer = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parent.footer.sizePolicy().hasHeightForWidth())
        parent.footer.setSizePolicy(sizePolicy)
        parent.footer.setObjectName("footer")
        parent.layoutButtons = QtWidgets.QHBoxLayout(parent.footer)
        parent.layoutButtons.setContentsMargins(0, 0, 0, 0)
        parent.layoutButtons.setSpacing(8)
        parent.layoutButtons.setObjectName("layoutButtons")
        parent.buttonPreview = QtWidgets.QPushButton(parent.footer)
        parent.buttonPreview.setAutoDefault(False)
        parent.buttonPreview.setObjectName("buttonPreview")
        parent.layoutButtons.addWidget(parent.buttonPreview)
        parent.buttonRecored = QtWidgets.QPushButton(parent.footer)
        parent.buttonRecored.setAutoDefault(False)
        parent.buttonRecored.setObjectName("buttonRecored")
        parent.layoutButtons.addWidget(parent.buttonRecored)
        parent.mainLayout.addWidget(parent.footer)

        self.retranslateUi(parent, Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, parent, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ZS  Playblast"))
        parent.FORMTAS.setText(_translate("Dialog", "FORMATS"))
        parent.CAMERAS.setText(_translate("Dialog", "CAMERAS"))
        parent.FRAMERANGE.setText(_translate("Dialog", "FRAME RANGE"))
        parent.buttonPreview.setText(_translate("Dialog", "PREVIEW"))
        parent.buttonRecored.setText(_translate("Dialog", "RECORD"))
